test:
	@echo " Testing..."
	python -m unittest model/unittest.py
	python -m unittest trajectory_optimization/iLQR/unittest.py
	python -m unittest trajectory_optimization/direct_collocation/unittest.py
	python -m unittest controllers/energy_shaping/unittest.py
	python -m unittest controllers/LQR/unittest.py
	python -m unittest controllers/iLQR/unittest.py
