name: Ubuntu22 Py3.10

on:                       # Run action when changes are pushed or pull requests are accepted
  push:
    branches-ignore: 
      - 'docs'            # Run on pushes to any branch except the doc hosting branch
  pull_request:
    branches-ignore:
      - 'docs'            # Run on pull requests to any branch except the doc hosting branch

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
   # ===========================
   #
   #         Ubuntu 22
   #
   # ===========================
   ub20:
     runs-on: ubuntu-22.04
     defaults:
       run:
         shell: bash
 
     steps:
     - name: Set up Git repository
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
     # Load environment variables from config.env =================
     - name: Load config variables into env
       run: |
         grep -v '^#' config.env | tr -d "[:blank:]" >> $GITHUB_ENV
     # Setup ======================================================
     - name: Set up Python 3.10
       if: env.run_tests == 'true'
       uses: actions/setup-python@v2
       with:
         python-version: "3.10"
     - name: Install pytest
       if: env.run_tests == 'true'
       run: |
         python -m pip install --upgrade pip
         pip install pytest
         # - name: Install coverage and emblem
         #   if: env.run_tests == 'true'
         #   run: |
         #     pip install coverage
         #     pip install emblem
     - name: Install Python dev headers
       if: env.run_tests == 'true'
       run: |
         sudo apt-get update
         sudo apt-get install python3-dev
         sudo apt install libpython3.10-dev
     - name: Install curl
       if: env.run_tests == 'true'
       run: |
         sudo apt-get install curl
     - name: Install dependencies
       if: env.run_tests == 'true'
       run: |
         sudo apt-get update
         sudo apt-get install --no-install-recommends \
           libpython3.10 libx11-6 libsm6 libxt6 libglib2.0-0 python3-tk
     - name: Install project
       if: env.run_tests == 'true'
       run: |
         make install
     # Run unit tests =============================================
     - name: Run tests
       if: env.run_tests == 'true'
       id: tests
       run: |
         # Run tests
         cd $codedir
         python -m pytest
